<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

/*
*	Implements hook_form_FORM_ID_alter().
*/

function request_form_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id){
	$form['name']['#attributes']['placeholder'] = 'Enter your Username here!';
}

/*
*	Implements hook_mail().
*/

function request_form_mail($key, &$message, $params){
	$options = ['langcode' => $message['langcode'],];

	switch($key){
		case 'submit':
			$from = \Drupal::config('system.site')->get('mail');
			$message['from'] = $from;
			$message['subject'] = t('Submit mail');
			$message['body'][] = $params['message'];
			break;
	}
}